export enum ModelGenerationStatus {
  UPLOADED = 'UPLOADED',
  QUEUED = 'QUEUED',
  EXTRACTING_FRAMES = 'EXTRACTING_FRAMES',
  RECONSTRUCTING = 'RECONSTRUCTING',
  GENERATING_MESH = 'GENERATING_MESH',
  TEXTURING = 'TEXTURING',
  EXPORTING_GLB = 'EXPORTING_GLB',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum ModelInputType {
  VIDEO = 'VIDEO',
  IMAGES = 'IMAGES',
}
